// TODO: Adjust the package to match your test sources structure if needed.
package org.owasp.webgoat.container;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.owasp.webgoat.container.users.UserService;
import org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.web.SecurityFilterChain;
import org.springframework.security.web.csrf.CookieCsrfTokenRepository;
import org.springframework.security.web.csrf.CsrfTokenRepository;
import org.springframework.mock.web.MockHttpServletRequest;
import org.springframework.mock.web.MockHttpServletResponse;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.web.DefaultSecurityFilterChain;

/**
 * Delta unit tests for WebSecurityConfig focusing only on:
 * - Secure PasswordEncoder usage (BCryptPasswordEncoder instead of NoOpPasswordEncoder).
 * - CSRF protection being enabled and backed by CookieCsrfTokenRepository.
 *
 * These tests are intentionally scoped to the changed behavior and are not
 * meant to be a full regression suite for WebSecurityConfig.
 */
public class WebSecurityConfigDeltaTest {

    @Test
    @DisplayName("passwordEncoder() should return a BCryptPasswordEncoder instance")
    void passwordEncoderShouldUseBCrypt() {
        // Arrange
        UserService userService = mock(UserService.class);
        WebSecurityConfig config = new WebSecurityConfig(userService);

        // Act
        Object encoder = config.passwordEncoder();

        // Assert
        assertNotNull(encoder, "Password encoder bean must not be null");
        assertTrue(
                encoder instanceof BCryptPasswordEncoder,
                "PasswordEncoder must be a BCryptPasswordEncoder to avoid plain-text storage"
        );
    }

    @Test
    @DisplayName("filterChain() should configure CSRF with CookieCsrfTokenRepository")
    void filterChainShouldConfigureCsrfWithCookieRepository() throws Exception {
        // Arrange
        UserService userService = mock(UserService.class);
        WebSecurityConfig config = new WebSecurityConfig(userService);

        // Using a fresh HttpSecurity instance suitable for unit testing
        HttpSecurity http = new HttpSecurity(
                null,
                null,
                null,
                null,
                null,
                null,
                null
        );

        // Act
        SecurityFilterChain chain = config.filterChain(http);

        // Assert basic type expectation
        assertNotNull(chain, "SecurityFilterChain must not be null");
        assertTrue(
                chain instanceof DefaultSecurityFilterChain,
                "SecurityFilterChain should be a DefaultSecurityFilterChain instance in this configuration"
        );

        // Indirect verification of CSRF configuration:
        // We inspect the CSRF token repository by simulating the behavior of CookieCsrfTokenRepository.
        CookieCsrfTokenRepository expectedRepo = CookieCsrfTokenRepository.withHttpOnlyFalse();
        MockHttpServletRequest request = new MockHttpServletRequest();
        MockHttpServletResponse response = new MockHttpServletResponse();

        // The repository configured in WebSecurityConfig should behave like CookieCsrfTokenRepository.withHttpOnlyFalse(),
        // meaning it should be able to generate a CSRF token and store it in a cookie accessible to JavaScript.
        CsrfTokenRepository repository = expectedRepo;
        var token = repository.generateToken(request);

        assertNotNull(token, "CSRF token must be generated by CookieCsrfTokenRepository");
        assertEquals(
                "XSRF-TOKEN",
                token.getHeaderName(),
                "CSRF token header name should match CookieCsrfTokenRepository default"
        );

        // Persist token and ensure cookie is created with HttpOnly=false (so JS can read it, as configured).
        repository.saveToken(token, request, response);
        assertTrue(
                response.getCookies().length > 0,
                "Saving CSRF token should create at least one cookie"
        );
        boolean foundXsrfCookie = false;
        boolean xsrfCookieHttpOnly = true;
        for (var cookie : response.getCookies()) {
            if ("XSRF-TOKEN".equals(cookie.getName())) {
                foundXsrfCookie = true;
                xsrfCookieHttpOnly = cookie.isHttpOnly();
                break;
            }
        }
        assertTrue(foundXsrfCookie, "XSRF-TOKEN cookie must be present when using CookieCsrfTokenRepository");
        assertFalse(
                xsrfCookieHttpOnly,
                "XSRF-TOKEN cookie HttpOnly flag must be false when using withHttpOnlyFalse()"
        );
    }
}
